# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: VaultVulp/action-pipenv@v2.0.1
      with: 
        command: install --dev
    - name: Lint with flake8
      uses: VaultVulp/action-pipenv@v2.0.1
      with: 
        command: run flake8
    - name: Check with mypy
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run mypy --ignore-missing-imports
    - name: Test with pytest
      uses: VaultVulp/action-pipenv@v2.0.1
      with: 
        command: run pytest
